### ISSUE TITLE
One thing needed to make it work in 1.9...

### ISSUE THREAD

**Issue by jondron** [ColdTrick/pages_tools#13]
Not so much an issue (though I'd love to see a 1.9+ version!) but an observation in case anyone else asks...

This plugin almost works in 1.9 as it is. All that needs to be changed for it to work without apparent error is to replace the two instances of 'fancybox' in js/site.php with 'colorbox' (or, presumably, to use the Fancybox plugin, though I have had mixed success with this in other plugins so am avoiding it on my site)

Jon

**Comment by hoogenm** [comment]
Thanking you for sharing this with other interested users. I tried this in Elgg 1.11 but unfortunately it didn't work for Elgg 1.11 (at least not with the combination of plugins we used, including Widget Manager 5.1). I would love to see a newer version of pages_tools as well (for Elgg 1.11+).

**Comment by jdalsem** [comment]
At this moment we have no plans to update this plugin for 1.11. This plugin requires a lot of work (mainly because it is behind a lot) and our focus is currently on other projects. If you really need this plugin updated and you are able to financially support this upgrade, please contact us at info@coldtrick.com
